apiVersion: v1
kind: Pod
metadata:
  name: nginx-no-limits
spec:
  containers:
    - name: nginx
      image: nginx:1.27-alpine

      resources:
        limits:
          cpu: "500m"
          memory: "256Mi"